/Source/Capsule/Construct
/NaI/setZ 10 cm
/NaI/Type 3x3

# Initialize run manager =======================================================
/run/initialize

#/vis/open RayTracer        # Makes a jpeg image
#/vis/open OGLIX
#/vis/open VRML1FILE         # To view, use    $ SceneViewer file.wrl
/vis/open VRML2FILE         # To view, use    $ view3dscene file.wrl

/vis/scene/create
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 20 150 deg
/vis/viewer/flush
